import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'

import ArrowLeftsNew from '../assets/ArrowLeftsNew.png'
import Profile from '../assets/avatar.png'
import Boxicon from '../assets/Boxicon.png'
import CloseIcon from '../assets/CloseIcon.png'
import CollectionAvatar from '../assets/CollectionAvatar.png'
import CollectionFour from '../assets/CollectionFour.png'
import DetailIcon from '../assets/details.svg'
import NFTIcon from '../assets/nfticon.png'
import RedArrowDown from '../assets/RedArrowDown.png'
import TopMoverOne from '../assets/TopMoverOne.png'
import TopMoverTwo from '../assets/TopMoverTwo.png'
import Twitter from '../assets/Twitter-icon.svg'
import { Header } from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'
const SteplineChart = dynamic(() => import('../components/Charts/Collection/SteplineChart'), {
  ssr: false,
})

const Collection: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aptos | Collection</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        {/* Sidebar  */}
        <div className='fixed top-0 left-0 h-full bg-white z-[1000]'>
          <Sidebar />
        </div>
        {/* End Sidebar  */}
        {/* Main Area  */}
        <div className='ml-[90px] w-full'>
          <div className='w-full pl-8 transition duration-500'>
            <Header />
            <div className='pr-8 pt-8'>
              <div className='max-w-[1650px] m-auto'>
                {/* ------------------------------------------------------ Profile Section ------------------------------------------------------ */}
                <div className='flex justify-between items-center flex-wrap'>
                  <div className='flex items-center basis-[400px]'>
                    <div className='cursor-pointer px-3 py-3 w-full bg-transparent border rounded-lg text-white border-[#1896894D] flex items-center justify-between'>
                      <span>24 hours</span>
                      <div className='relative'>
                        <svg
                          width='10'
                          height='8'
                          viewBox='0 0 10 8'
                          fill='none'
                          xmlns='http://www.w3.org/2000/svg'
                        >
                          <path
                            d='M9.66458 0.875H0.335417C0.0555991 0.875 -0.100645 1.18162 0.0726438 1.39095L4.73723 7.00449C4.87074 7.16517 5.12784 7.16517 5.26277 7.00449L9.92736 1.39095C10.1006 1.18162 9.9444 0.875 9.66458 0.875Z'
                            fill='white'
                            fillOpacity='0.6'
                          />
                        </svg>
                      </div>
                    </div>
                    <button type='button' className='text-white ml-4'>
                      <Image src={DetailIcon} alt='DetailIcon' />
                    </button>
                  </div>
                  <div className='flex items-center'>
                    <button type='button' className='relative'>
                      <svg
                        width='20'
                        height='22'
                        viewBox='0 0 20 22'
                        fill='none'
                        xmlns='http://www.w3.org/2000/svg'
                      >
                        <path
                          d='M10 22C11.5177 22 12.7487 20.7689 12.7487 19.25H7.25132C7.25132 20.7689 8.48237 22 10 22ZM19.2551 15.5671C18.4249 14.6751 16.8716 13.3332 16.8716 8.9375C16.8716 5.59883 14.5307 2.92617 11.3742 2.27047V1.375C11.3742 0.615742 10.7589 0 10 0C9.2412 0 8.62589 0.615742 8.62589 1.375V2.27047C5.4694 2.92617 3.12847 5.59883 3.12847 8.9375C3.12847 13.3332 1.57515 14.6751 0.744991 15.5671C0.487178 15.8443 0.372881 16.1756 0.37503 16.5C0.379756 17.2047 0.932764 17.875 1.75433 17.875H18.2457C19.0673 17.875 19.6207 17.2047 19.625 16.5C19.6272 16.1756 19.5129 15.8439 19.2551 15.5671Z'
                          fill='white'
                          fillOpacity='0.8'
                        />
                      </svg>
                      <div className='top-[-4px] right-[-4px] absolute h-[12px] w-[12px] rounded-full bg-white flex items-center justify-center'>
                        <div className='bg-[#FF9703] h-[8px] w-[8px] rounded-full'></div>
                      </div>
                    </button>
                    <div className='w-[1px] h-[40px] mx-6 bg-white/[0.2]'></div>
                    <span className='text-white'>Mertin De</span>
                    <div className='cursor-pointer h-[50px] w-[50px] rounded-full bg-white ml-3 flex items-center justify-center'>
                      <div className='h-[48px] w-[48px] rounded-full bg-black'>
                        <div className='h-[47px] w-[47px] flex items-center justify-center overflow-hidden'>
                          <Image src={Profile} alt='Profile' className='rounded-full' />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* ------------------------------------------------------ Profile Section ------------------------------------------------------ */}
                <div className='pt-8'>
                  <div className='flex p-4 bg-lightblack rounded-[18px] justify-between'>
                    <div className='bg-[#141414] basis-[25%] 2xl:basis-[22%] py-8 pl-4 rounded-lg'>
                      <div className='flex items-center'>
                        <Image src={CollectionAvatar} alt='Skull' />
                        <div className='ml-4'>
                          <span className='text-[#FFFFFFB2] 2xl:text-[1.125rem] text-[0.813rem] flex items-center'>
                            Collection
                            <a
                              href='https://twittter.com/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block ml-2'
                            >
                              <Image src={Twitter} alt='Twitter' />
                            </a>
                          </span>
                          <p className='text-[#FFFFFFCC] text-[1.5rem] mt-[4px]'>Aptos Power Man</p>
                        </div>
                      </div>
                    </div>
                    <div className='bg-[#141414] basis-[37%] 2xl:basis-[38.5%] py-8 px-4 rounded-lg'>
                      <div className='flex 2xl:items-center justify-between'>
                        <div>
                          <span className='text-[#FFFFFFB2] 2xl:text-[1.125rem] text-[0.813rem]'>
                            Trend
                          </span>
                          <p className='text-[#FFFFFFCC] text-[1.5rem]'>Last 24 Hours</p>
                        </div>
                        <div className='2xl:flex items-center justify-between 2xl:basis-[65%]'>
                          <div className='relative flex items-center'>
                            <Image src={RedArrowDown} alt='RedArrowDown'></Image>
                            <p className='2xl:text-[1rem] text-[0.875rem] text-white ml-2'>
                              -5.3%{' '}
                              <span className='text-[#FFFFFFB2] 2xl:text-[1rem] text-[0.875rem]'>
                                Floor Price
                              </span>
                            </p>
                          </div>
                          <div className='relative flex items-center mt-1 2xl:mt-0 2xl:ml-2'>
                            <Image src={RedArrowDown} alt='RedArrowDown'></Image>
                            <p className='2xl:text-[1rem] text-[0.875rem] text-white ml-2'>
                              -5.3%{' '}
                              <span className='text-[#FFFFFFB2] 2xl:text-[1rem] text-[0.875rem]'>
                                Floor Price
                              </span>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className='bg-[#141414] basis-[37%] 2xl:basis-[38.5%] py-8 pl-4 rounded-lg'>
                      <div className='flex items-center'>
                        <div>
                          <span className='text-[#FFFFFFB2] 2xl:text-[1.125rem] text-[0.813rem]'>
                            Average Floor Price
                          </span>
                          <p className='text-[#FFFFFFCC] text-[1.5rem]'>Average Hourly FP Index</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='pt-8'>
                  <div className='p-4 bg-lightblack rounded-[18px]'>
                    <div className='flex items-center justify-end text-white'>
                      <div className='flex items-center mr-4 mb-4'>
                        <input id='radio1' type='radio' name='radio' className='hidden' />
                        <label
                          htmlFor='radio1'
                          className='flex items-center cursor-pointer text-[0.875rem]'
                        >
                          <span className='w-4 h-4 inline-block mr-1 rounded-full border border-[#F7809D]'></span>
                          Topaz Floor Price
                        </label>
                      </div>
                      <div className='flex items-center mr-4 mb-4'>
                        <input id='radio2' type='radio' name='radio' className='hidden' />
                        <label
                          htmlFor='radio2'
                          className='flex items-center cursor-pointer text-[0.875rem]'
                        >
                          <span className='w-4 h-4 inline-block mr-1 rounded-full border border-[#58F1BB]'></span>
                          Listed Count
                        </label>
                      </div>
                      <div className='flex items-center mr-4 mb-4'>
                        <input id='radio3' type='radio' name='radio' className='hidden' />
                        <label
                          htmlFor='radio3'
                          className='flex items-center cursor-pointer text-[0.875rem]'
                        >
                          <span className='w-4 h-4 inline-block mr-1 rounded-full border border-[#71ADFF]'></span>
                          Mentions
                        </label>
                      </div>
                      <div className='flex items-center mr-4 mb-4'>
                        <input id='radio4' type='radio' name='radio' className='hidden' />
                        <label
                          htmlFor='radio4'
                          className='flex items-center cursor-pointer text-[0.875rem]'
                        >
                          <span className='w-4 h-4 inline-block mr-1 rounded-full border border-[#B5A9FE]'></span>
                          Volume
                        </label>
                      </div>
                    </div>
                    <div className='h-[375px] 2xl:h-[400px]'>
                      <SteplineChart />
                    </div>
                  </div>
                </div>
                <div className='pt-8 pb-8'>
                  <div className='flex gap-[2%]'>
                    <div className='p-4 bg-lightblack rounded-[18px] basis-[69%]'>
                      <div className='flex items-center justify-between'>
                        <h4 className='text-white text-[1.25rem]'>Selected Collections</h4>
                        <div className='cursor-pointer px-3 py-2 w-[180px] bg-transparent border rounded-lg text-white border-[#1896894D] flex items-center justify-between'>
                          <span>Topaz Floor price</span>
                          <div className='relative rotate-[-90deg] mt-[1px]'>
                            <Image src={ArrowLeftsNew} alt='ArrowLeftsNew.png' />
                          </div>
                        </div>
                      </div>
                      {/* Table  */}
                      <div className='mt-6 rounded-tl-[14px] rounded-tr-[14px] overflow-hidden'>
                        <table className='w-full'>
                          <thead>
                            <tr className='text-left text-white bg-[#141414]'>
                              <th className='py-6 px-3 text-white font-normal'>Collections</th>
                              <th className='py-6 px-3 text-white font-normal'>96h</th>
                              <th className='py-6 px-3 text-white font-normal'>72h</th>
                              <th className='py-6 px-3 text-white font-normal'>48h</th>
                              <th className='py-6 px-3 text-white font-normal'>24h</th>
                              <th className='py-6 px-3 text-white font-normal'>Latest</th>
                              <th className='py-6 px-3 text-white font-normal'>24h%</th>
                              <th className='py-6 px-3 text-white font-normal'></th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td className='py-6 px-3'>
                                <div className='flex items-center'>
                                  <div className='flex items-center mr-2'>
                                    <input
                                      id='Collection1'
                                      type='radio'
                                      name='radio'
                                      className='hidden'
                                    />
                                    <label
                                      htmlFor='Collection1'
                                      className='flex items-center cursor-pointer text-[0.875rem]'
                                    >
                                      <span className='w-4 h-4 inline-block mr-1 rounded-full border border-[#F7809D]'></span>
                                    </label>
                                  </div>
                                  <Image src={CollectionFour} alt='Collection' />
                                  <div className='ml-4'>
                                    <span className='text-[#FFFFFFB2] text-[1rem]'>Aptomingos</span>
                                    <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptomingos</p>
                                  </div>
                                </div>
                              </td>
                              <td className='py-6 px-3 text-[#FFFFFFCC]'>
                                <div className='flex items-center'>
                                  <div className='relative'>
                                    <Image src={NFTIcon} alt='NFTIcon'></Image>
                                  </div>
                                  <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>4.8</p>
                                </div>
                              </td>
                              <td className='py-6 px-3'>
                                <div className='flex items-center'>
                                  <div className='relative'>
                                    <Image src={NFTIcon} alt='NFTIcon'></Image>
                                  </div>
                                  <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>6.5</p>
                                </div>
                              </td>
                              <td className='py-6 px-3'>
                                <div className='flex items-center'>
                                  <div className='relative'>
                                    <Image src={NFTIcon} alt='NFTIcon'></Image>
                                  </div>
                                  <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>6.3</p>
                                </div>
                              </td>
                              <td className='py-6 px-3'>
                                <div className='flex items-center'>
                                  <div className='relative'>
                                    <Image src={NFTIcon} alt='NFTIcon'></Image>
                                  </div>
                                  <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>7.2</p>
                                </div>
                              </td>
                              <td className='py-6 px-3'>
                                <div className='flex items-center'>
                                  <div className='relative'>
                                    <Image src={NFTIcon} alt='NFTIcon'></Image>
                                  </div>
                                  <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>7.2</p>
                                </div>
                              </td>
                              <td className='py-6 px-3'>
                                <p className='ml-1 mt-[2px] text-darkgreen text-[1rem]'>+0.14%</p>
                              </td>
                              <td className='py-6 px-3'>
                                <button type='button'>
                                  <Image src={CloseIcon} alt='CloseIcon' />
                                </button>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      {/* End Table  */}
                    </div>
                    <div className='p-4 bg-lightblack rounded-[18px] basis-[29%]'>
                      <h4 className='text-white text-[1.25rem] mb-3 mt-2'>
                        Top Floor Movers &#40;Last hour&#41;
                      </h4>
                      <div className='mt-2 flex items-center justify-between bg-[#14141433] border border-[#FFFFFF05] p-3 rounded-lg'>
                        <div className='flex items-center'>
                          <Image src={TopMoverOne} alt='TopMoverOne' />
                          <div className='ml-2'>
                            <span className='text-[#FFFFFFE5] text-[1.125rem]'>BabyApetos</span>
                            <p className='text-[#FFFFFF99] text-[0.938rem]'>
                              0.04 $APT <span className='text-[#00DA9D]'>+33.33%</span>
                            </p>
                          </div>
                        </div>
                        <div className='relative'>
                          <Image src={Boxicon} alt='Boxicon' />
                        </div>
                      </div>
                      <div className='mt-2 flex items-center justify-between bg-[#14141433] border border-[#FFFFFF05] p-3 rounded-lg'>
                        <div className='flex items-center'>
                          <Image src={TopMoverTwo} alt='TopMoverOne' />
                          <div className='ml-2'>
                            <span className='text-[#FFFFFFE5] text-[1.125rem]'>
                              Lazy Clown Buddies
                            </span>
                            <p className='text-[#FFFFFF99] text-[0.938rem]'>
                              0.04 $APT <span className='text-[#00DA9D]'>+33.33%</span>
                            </p>
                          </div>
                        </div>
                        <div className='relative'>
                          <Image src={Boxicon} alt='Boxicon' />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* End Main Area  */}
        </div>
      </div>
    </div>
  )
}

export default Collection
