import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

import Arrow from '../assets/Arrow.svg'
import DetailIcon from '../assets/details.svg'
import NFTEight from '../assets/NFTEight.png'
import NFTEleven from '../assets/NFTEleven.png'
import NFTFive from '../assets/NFTFive.png'
import NFTFivteen from '../assets/NFTFivteen.png'
import NFTFour from '../assets/NFTFour.png'
import NFTFourteen from '../assets/NFTFourteen.png'
import NFTIcon from '../assets/nfticon.png'
import NFTNine from '../assets/NFTNine.png'
import NFTOne from '../assets/NFTOne.png'
import NFTSeven from '../assets/NFTSeven.png'
import NFTSix from '../assets/NFTSix.png'
import NFTTen from '../assets/NFTTen.png'
import NFTThirteen from '../assets/NFTThirteenn.png'
import NFTThree from '../assets/NFTThree.png'
import NFTTwelve from '../assets/NFTTwelve.png'
import NFTTwo from '../assets/NFTTwo.png'
import Twitter from '../assets/Twitter-icon.svg'
import { Header } from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'

const LineChart = dynamic(() => import('../components/Charts/Homepage/LineChart'), { ssr: false })
const DateTimeChart = dynamic(() => import('../components/Charts/Homepage/DateTimeChart'), {
  ssr: false,
})
const ColumnChart = dynamic(() => import('../components/Charts/Homepage/ColumnChart'), {
  ssr: false,
})
const BarChart = dynamic(() => import('../components/Charts/Homepage/BarChart'), { ssr: false })

const Home: NextPage = () => {
  useEffect(() => {
    //0xe32a79149395a3cb3611fd30f748be07c49adb10c36e4ff7cda52708e7ac025a topaz listing table handle
  }, [])
  return (
    <div>
      <Head>
        <title>Aptos | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        {/* Sidebar  */}
        <div className='fixed top-0 left-0 h-full bg-white z-[1000]'>
          <Sidebar />
        </div>
        {/* End Sidebar  */}

        {/* Main Area  */}
        <div className='ml-[90px] w-full'>
          <div className='w-full pl-8 transition duration-500'>
            <Header />
            <div className='pr-8 pt-8'>
              <div className='max-w-[1650px] m-auto'>
                {/* ------------------------------------------------------ NFT Section ------------------------------------------------------ */}
                <div className='flex justify-between flex-wrap gap-[2%]'>
                  {/* NFT Wrap One */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[23.5%] basis-[49%] mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Smart Money Inflow</h4>
                      <div className='flex'>
                        <button className='text-white'>1D</button>
                        <button className='text-white/[0.5] ml-4'>1W</button>
                      </div>
                    </div>
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTOne} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Meta Pigs</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTTwo} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>My Duckts</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTThree} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Undead</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTFour} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Pontem Space Pirtates</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                  </div>
                  {/* End NFT Wrap One */}
                  {/* NFT Wrap Two */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[23.5%] basis-[49%] mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Top Social Buying</h4>
                      <div className='flex'>
                        <button className='text-white'>1D</button>
                        <button className='text-white/[0.5] ml-4'>1W</button>
                      </div>
                    </div>
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTFive} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>AptoPunks</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTSix} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Plants</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTSeven} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Claw Machine</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTEight} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Bruh Bears</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                  </div>
                  {/* End NFT Wrap Two */}
                  {/* NFT Wrap Three */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[23.5%]  basis-[49%] mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Top Movers</h4>
                      <div className='flex'>
                        <button className='text-white'>1D</button>
                        <button className='text-white/[0.5] ml-4'>1W</button>
                      </div>
                    </div>
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTNine} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Baby Apetos</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTTen} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Piggy Cyborgs</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTEleven} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Farmlands</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTTwelve} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptomingos</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                  </div>
                  {/* End NFT Wrap Three */}
                  {/* NFT Wrap Four */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[23.5%] basis-[49%] mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Smart Outflow</h4>
                      <div className='flex'>
                        <button className='text-white'>1D</button>
                        <button className='text-white/[0.5] ml-4'>1W</button>
                      </div>
                    </div>
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTThirteen} alt='NFT'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Rats</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTFourteen} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Anime</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTFivteen} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos Toad Overload</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkred'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                    {/* Card Row  */}
                    <div className='flex justify-between mt-4'>
                      <div className='flex items-center'>
                        <div className='relative mr-2'>
                          <Image src={NFTFour} alt='NFTOne'></Image>
                        </div>
                        <div>
                          <h6 className='text-[#FFFFFFB2]'>Aptos NFT</h6>
                          <span className='text-[#FFFFFFB2] text-[0.875rem]'>Floor Price</span>
                          <div className='flex items-center mt-[-2px]'>
                            <div className='relative'>
                              <Image src={NFTIcon} alt='NFTIcon'></Image>
                            </div>
                            <div className='flex ml-1 mt-[2px]'>
                              <p className='text-white text-[0.813rem]'>0.65</p>
                              <p className='ml-1 block text-[0.813rem] text-darkgreen'>+32.65%</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='self-end'>
                        <p className='text-white/[0.5]'>1D Volume</p>
                        <div className='flex items-center mt-[-2px]'>
                          <div className='relative'>
                            <Image src={NFTIcon} alt='NFTIcon'></Image>
                          </div>
                          <div className='flex ml-1 mt-[2px]'>
                            <p className='text-white text-[0.813rem]'>0.65</p>
                            <p className='ml-1 block text-[0.813rem] text-white'>+32.65%</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* End Card Row  */}
                  </div>
                  {/* End NFT Wrap Four */}
                </div>
                {/* ------------------------------------------------------ End NFT Section ------------------------------------------------------ */}
                {/* ------------------------------------------------------ Graph Section ------------------------------------------------------ */}
                {/* Graph Section */}
                <div className='flex justify-between flex-wrap gap-[1%]'>
                  {/* Graph Wrap One */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[49%] w-full mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Marketplace Volume</h4>
                      <div className='flex'>
                        <button className='text-white'>
                          <Image src={DetailIcon} alt='DetailIcon' />
                        </button>
                        <a
                          href='https://twittter.com/'
                          target='_blank'
                          rel='noreferrer'
                          className='inline-block pt-2 text-white/[0.5] ml-2 px-2 rounded-md bg-[#FFFFFF1C]'
                        >
                          <Image src={Twitter} alt='Twitter' />
                        </a>
                        <button className='text-white/[0.5] ml-2 flex items-center px-2 rounded-md bg-[#FFFFFF1C]'>
                          <span className='text-[0.875rem]'>1M</span>
                          <Image src={Arrow} alt='arrow' className='ml-1' />
                        </button>
                      </div>
                    </div>
                    <div className='flex justify-between mt-8 border border-[#FFFFFF05] p-1 rounded-md flex-wrap'>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>APT.V2</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>37.92M</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Aptos</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>230,109</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Topaz</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>144,426</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Souffl3</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>12,520</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Other</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>32,152</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                    </div>
                    <div className='flex items-center justify-end text-white pt-6'>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v1'>
                        Topaz
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v2'>
                        Bluemove
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v3'>
                        souffl3
                      </button>
                    </div>
                    <div className='mt-4 min-h-[375px]'>
                      <BarChart />
                    </div>
                  </div>
                  {/* Graph Wrap Two */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[49%] w-full mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>
                        Marketplace Volume &#40;Sales&#41;
                      </h4>
                      <div className='flex'>
                        <button className='text-white'>
                          <Image src={DetailIcon} alt='DetailIcon' />
                        </button>
                        <a
                          href='https://twittter.com/'
                          target='_blank'
                          rel='noreferrer'
                          className='inline-block pt-2 text-white/[0.5] ml-2 px-2 rounded-md bg-[#FFFFFF1C]'
                        >
                          <Image src={Twitter} alt='Twitter' />
                        </a>
                        <button className='text-white/[0.5] ml-2 flex items-center px-2 rounded-md bg-[#FFFFFF1C]'>
                          <span className='text-[0.875rem]'>1M</span>
                          <Image src={Arrow} alt='arrow' className='ml-1' />
                        </button>
                      </div>
                    </div>
                    <div className='flex justify-between mt-8 border border-[#FFFFFF05] p-1 rounded-md'>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>APT.V2</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>37.92M</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Aptos</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>230,109</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Topaz</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>144,426</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Souffl3</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>12,520</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Other</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>32,152</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                    </div>
                    <div className='flex items-center justify-end text-white pt-6'>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v1'>
                        Topaz
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v2'>
                        Bluemove
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v3'>
                        souffl3
                      </button>
                    </div>
                    <div className='mt-4 min-h-[375px]'>
                      <ColumnChart />
                    </div>
                  </div>
                  {/* Graph Wrap Three */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[49%] w-full mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Daily Transacting Owners</h4>
                      <div className='flex'>
                        <button className='text-white'>
                          <Image src={DetailIcon} alt='DetailIcon' />
                        </button>
                        <a
                          href='https://twittter.com/'
                          target='_blank'
                          rel='noreferrer'
                          className='inline-block pt-2 text-white/[0.5] ml-2 px-2 rounded-md bg-[#FFFFFF1C]'
                        >
                          <Image src={Twitter} alt='Twitter' />
                        </a>
                        <button className='text-white/[0.5] ml-2 flex items-center px-2 rounded-md bg-[#FFFFFF1C]'>
                          <span className='text-[0.875rem]'>1M</span>
                          <Image src={Arrow} alt='arrow' className='ml-1' />
                        </button>
                      </div>
                    </div>
                    <div className='flex justify-between mt-8 border border-[#FFFFFF05] p-1 rounded-md'>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>APT.V2</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>37.92M</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Aptos</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>230,109</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Topaz</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>144,426</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Souffl3</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>12,520</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Other</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>32,152</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                    </div>
                    <div className='flex items-center justify-end text-white pt-6'>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v1'>
                        Topaz
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v2'>
                        Bluemove
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v3'>
                        souffl3
                      </button>
                    </div>
                    <div className='mt-4 min-h-[375px]'>
                      <LineChart />
                    </div>
                  </div>
                  {/* Graph Wrap Four */}
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[49%] w-full mb-8'>
                    <div className='flex justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Daily NFT Mints</h4>
                      <div className='flex'>
                        <button className='text-white'>
                          <Image src={DetailIcon} alt='DetailIcon' />
                        </button>
                        <a
                          href='https://twittter.com/'
                          target='_blank'
                          rel='noreferrer'
                          className='inline-block pt-2 text-white/[0.5] ml-2 px-2 rounded-md bg-[#FFFFFF1C]'
                        >
                          <Image src={Twitter} alt='Twitter' />
                        </a>
                        <button className='text-white/[0.5] ml-2 flex items-center px-2 rounded-md bg-[#FFFFFF1C]'>
                          <span className='text-[0.875rem]'>1M</span>
                          <Image src={Arrow} alt='arrow' className='ml-1' />
                        </button>
                      </div>
                    </div>
                    <div className='flex justify-between mt-8 border border-[#FFFFFF05] p-1 rounded-md'>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>APT.V2</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>37.92M</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Aptos</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>230,109</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Topaz</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>144,426</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Souffl3</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>12,520</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                      <div className='bg-[#141414] basis-[19%] text-center py-3 rounded-lg'>
                        <p className='text-[#FFFFFF99]'>Other</p>
                        <p className='text-darkgreen font-bold text-[1.125rem] py-1'>32,152</p>
                        <p className='text-[#FFFFFF99]'>Total</p>
                      </div>
                    </div>
                    <div className='flex items-center justify-end text-white pt-6'>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v1'>
                        Topaz
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v2'>
                        Bluemove
                      </button>
                      <button className='text-[0.75rem] ml-2 py-1 px-3 bg-red rounded-full graph-btn-gradient-v3'>
                        souffl3
                      </button>
                    </div>
                    <div className='mt-4 min-h-[375px]'>
                      <DateTimeChart />
                    </div>
                  </div>
                </div>
                {/* ------------------------------------------------------ End Graph Section ------------------------------------------------------ */}
              </div>
            </div>
          </div>
          {/* End Main Area  */}
        </div>
      </div>
    </div>
  )
}

export default Home
