import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Arrow from '../assets/Arrow.svg'
import ArrowLefts from '../assets/ArrowLeftsNew.png'
import ArrowRight from '../assets/ArrowRightNew.png'
import CollectionEight from '../assets/CollectionEight.png'
import CollectionEleven from '../assets/CollectionEleven.png'
import CollectionFive from '../assets/CollectionFive.png'
import CollectionFour from '../assets/CollectionFour.png'
import CollectionNine from '../assets/CollectionNine.png'
import CollectionOne from '../assets/CollectionOne.png'
import CollectionTwo from '../assets/CollectionSecond.png'
import CollectionSeven from '../assets/CollectionSeven.png'
import CollectionSix from '../assets/CollectionSix.png'
import CollectionTen from '../assets/CollectionTenth.png'
import CollectionThree from '../assets/CollectionThree.png'
import CollectionTwelve from '../assets/CollectionTwelve.png'
import DetailIcon from '../assets/details.svg'
import FollowerOne from '../assets/ListedImg.png'
import FollowerTwo from '../assets/ListedImg2.png'
import FollowerThree from '../assets/ListedImg3.png'
import NFTIcon from '../assets/nfticon.png'
import TableGraphIcon from '../assets/table-graph-icon.png'
import { Header } from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'

const Social: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aptos | Twitter Signals</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        {/* Sidebar  */}
        <div className='fixed top-0 left-0 h-full bg-white z-[1000]'>
          <Sidebar />
        </div>
        {/* End Sidebar  */}
        {/* Main Area  */}
        <div className='ml-[90px] w-full'>
          <div className='w-full pl-8 transition duration-500'>
            <Header />
            <div className='pr-8 pt-8 pb-8'>
              <div className='max-w-[1650px] m-auto'>
                {/* ------------------------------------------------------ Signal Section ------------------------------------------------------ */}
                <div className='2xl:flex justify-between items-start flex-wrap gap-[1%]'>
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[67%] mb-8 2xl:mb-0'>
                    <div className='flex items-center justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Twitter Signals</h4>
                      <button type='button' className='text-white ml-4'>
                        <Image src={DetailIcon} alt='DetailIcon' />
                      </button>
                    </div>
                    <div className='mt-6 rounded-tl-[14px] rounded-tr-[14px] overflow-hidden'>
                      <table className='w-full'>
                        <thead>
                          <tr className='text-left text-white bg-[#242424]'>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>Call</th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>Collection</th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>Probability</th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>
                              FP When Called
                            </th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>
                              Highest Profit
                            </th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>
                              Highest Profit Point
                            </th>
                            <th className='py-6 px-3 text-[#FFFFFF99] font-normal'>Inspect</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>2h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionOne} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>
                                    FP change last 24h
                                  </span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptos_rats</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Two  */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>10h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionTwo} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>
                                    Aptos Doodles
                                  </span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptos_doodles</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Three  */}
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>24h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionThree} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>
                                    Aptos Farmlands
                                  </span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>
                                    @aptos_farmlands
                                  </p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Four   */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>6h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionFour} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Aptomingos</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptomingos</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Five  */}
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>2m</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionFive} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>
                                    The Bored Aptos Yacht...
                                  </span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptos_bored</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Six  */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>20h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionSix} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>
                                    Aptos Toad Overload
                                  </span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>
                                    @aptos_toad overload
                                  </p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Seven  */}
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>1h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionSeven} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Aptos Ghosts</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptos_ghosts</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row EIght  */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>17h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionEight} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Aptos Punks</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@aptos_punks</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Nine  */}
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>5d</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionNine} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Claw Machine</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@claw_machine</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Ten   */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>7h</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionTen} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Dope Deerz</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@dope_deerz</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Eleven  */}
                          <tr>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>2d</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionEleven} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>Shikoku</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@shikoku</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                          {/* Row Twelve */}
                          <tr className='bg-[#151515] border border-[#FFFFFF03]'>
                            <td className='py-6 px-3 text-[1rem] text-[#FFFFFFCC]'>5m</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <Image src={CollectionTwelve} alt='Collection' />
                                <div className='ml-4'>
                                  <span className='text-[#FFFFFFB2] text-[1rem]'>My Duks</span>
                                  <p className='text-[#FFFFFFB2] text-[0.875rem]'>@my_duks</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>93.18%</td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <p className='ml-1 mt-[2px] text-[#FFFFFFCC] text-[1rem]'>0.49</p>
                              </div>
                            </td>
                            <td className='py-6 px-3'>
                              <div className='flex items-center'>
                                <div className='relative'>
                                  <Image src={NFTIcon} alt='NFTIcon'></Image>
                                </div>
                                <div className='flex ml-1 mt-[2px]'>
                                  <p className='text-[#FFFFFFCC] text-[1rem]'>0.65</p>
                                  <p className='ml-1 block text-[1rem] text-darkgreen'>+32.65%</p>
                                </div>
                              </div>
                            </td>
                            <td className='py-6 px-3 text-[#FFFFFFCC]'>Nov 17, 13:11</td>
                            <td className='py-6 px-3'>
                              <Image src={TableGraphIcon} alt='TableGraphIcon' />
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <div className='flex justify-end items-center text-[#FFFFFFCC] mt-3'>
                      <div className='flex items-center'>
                        <p className='flex items-center'>
                          Rows per page: <span>&nbsp;10</span>{' '}
                          <button type='button' className='rotate-[-90deg] ml-2'>
                            <Image src={ArrowLefts} alt='arrow' />
                          </button>
                        </p>
                        <p className='mx-4'>
                          1-2 of <span>2</span>
                        </p>
                        <div className='flex'>
                          <button type='button'>
                            <Image src={ArrowLefts} alt='arrows' />
                          </button>
                          <button type='button' className='ml-3'>
                            <Image src={ArrowRight} alt='arrows' />
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className='p-4 bg-lightblack rounded-[18px] 2xl:basis-[31%]'>
                    <div className='flex items-center justify-between'>
                      <h4 className='text-white text-[1.25rem]'>Social Activity</h4>
                      <button type='button' className='text-white ml-4'>
                        <Image src={DetailIcon} alt='DetailIcon' />
                      </button>
                    </div>
                    <div className='mt-6 rounded-tl-[14px] rounded-tr-[14px] overflow-hidden'>
                      <div className='flex items-center justify-between bg-[#242424] py-4 px-3'>
                        <h4 className='text-[#FFFFFF99] text-[1rem]'>Social Activity</h4>
                        <button className='text-[#FFFFFF99] flex items-center justify-between px-2 py-[6px] rounded-md border border-[#FFFFFF1A]'>
                          <span className='text-[0.875rem] 2xl:mt-[2px]'>All</span>
                          <Image src={Arrow} alt='arrow' className='ml-3' />
                        </button>
                      </div>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={FollowerOne} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={FollowerTwo} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={CollectionFour} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={CollectionEight} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={CollectionNine} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={CollectionTwelve} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={FollowerThree} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={CollectionSix} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={CollectionFive} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={CollectionTen} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between'>
                      <div className='flex items-center'>
                        <Image src={CollectionThree} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                    <div className='py-7 px-2 flex items-center justify-between bg-[#141414]'>
                      <div className='flex items-center'>
                        <Image src={CollectionTwo} alt='Collection' width={50} />
                        <div className='ml-2'>
                          <p className='text-[#FFFFFFB2] text-[0.875rem] flex items-center'>
                            @aptos_rats
                            <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                            2h
                          </p>
                          <p className='text-[0.75rem] text-[#FFFFFFB2] flex items-center'>
                            Listed{' '}
                            <a
                              href='/'
                              target='_blank'
                              rel='noreferrer'
                              className='inline-block mx-1 underline'
                            >
                              Aptos
                            </a>
                            for 244.00
                          </p>
                        </div>
                      </div>
                      <p className='text-[#FFFFFFB2] 2xl:text-[0.75rem] text-[0.75rem] flex items-center'>
                        200 Following
                        <span className='block bg-[#FFFFFFB2] h-[7px] w-[7px] rounded mx-2'></span>
                        580 Followers
                      </p>
                    </div>
                  </div>
                </div>
                {/* ------------------------------------------------------ Signal Section ------------------------------------------------------ */}
              </div>
            </div>
          </div>
          {/* End Main Area  */}
        </div>
      </div>
    </div>
  )
}

export default Social
